---
title: "Apuntes Git y RMarkdown"
author: "Patricio Said"
date: "25 de mayo de 2019"

output: github_document
---

***
<!-- as? se ponen comentarios en rmarkdown--> 
### Un poco de documentaci?n: 
- [Cheat sheet de Rmarkdown](https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf) 
- [Sintaxis para documentos en GitHub (markdown)](https://help.github.com/en/articles/basic-writing-and-formatting-syntax)
- P?gina de Git, manuales, libros, documentos en espa?ol: [got-scm.com](https://git-scm.com/book/es/v2)
- Un blog de apuntes corto de [Git/GitHub](https://libreim.github.io/blog/2014/02/23/manualgit/)
- Un repositorio de apuntes: [aprende Git "curso"](https://github.com/JJ/aprende-git)
- Otro repositorio de apuntes: [aprende Git](https://github.com/DGIIMUnderground/DGIIM1)
- Aprender Git y GitHut con [Codecademy](https://www.codecademy.com/courses/learn-git/)
- Libro [blogdown: Creating Websites with R Markdown](https://bookdown.org/yihui/blogdown/) y el [Repo. en GitHub](https://github.com/rstudio/blogdown)
- Libro [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/) (**VER**)
- Instrucciones de GitHub / RStudio (https://resources.github.com/whitepapers/github-and-rstudio/) (**VER**)
- RMarkdown formato de documentos GitHub (https://rmarkdown.rstudio.com/github_document_format.html) (**VER**)

***

**Nota:**

> El **objetivo** de este documento se enfoca en la creaci?n y publicaci?n de un post formato blog. Se mostrar? paso a paso, desde la escritura en Rmarkdown hasta publicaci?n en GitHub.

## Elementos de RMarkdown

RMarkdown y GitHub utilizan la sintaxis de Markdown para reproducir facilmente formatos de escrituras (html en este caso). Para escribir un documento bien estructurado es fundamental conocer los elementos b?sicos para crear un texto: t?tulos, subt?tulos, listas, letras en cursivas o en negritas, citas, etc. Por ejemplo en RMarkdown, para diferenciar un parafo de otro se deben separar por una lina de c?digo vac?a.

### Sintaxis b?sicas

A continuaci?n se presenta algunas de las principales sintaxis y en la linea siguiente la salida o (render) correspondiente:

`# Ejemplo de t?tulo grande`

# Ejemplo de t?tulo grande

`### Ejemplo de un sub t?tulo`

### Ejemplo de un sub t?tulo

`*cursiva*` y `*negrita*`

*cursiva* y  **negrita**

<code>\`formato c?digo\`</code>

`formato c?digo`

`superindice^2^ y subindice~2~`

superindice^2^ y subindice~2~

`~~tachado~~`

~~tachado~~

\* \_ \\

`Poner signos: \* \_ \\` 

Poner signos: \* \_ \\

`--`

--

`---`

---

`Ecuaci?n en linea $A=\pi*r^2$`

Ecuaci?n en linea $A=\pi*r^2$

`$$A=\pi*r^2$$`

$$A=\pi*r^2$$

`Saltar a [Ejemplo de t?tulo grande]`

Saltar a [Ejemplo de t?tulo grande] 

`> Cita`

> Cita

`<https://psaid.shinyapps.io/AInsigne/>`

<https://psaid.shinyapps.io/AInsigne/>

`[Link a AInsigne](https://psaid.shinyapps.io/AInsigne/)`

[Link a AInsigne](https://psaid.shinyapps.io/AInsigne/)


 
`  * item de lista`
`  * otro item`
`      + sub item`
`          - sub sub item `

 * item de lista
 * otro item
    + sub item
        - sub sub item
      
`* otro item`

* otro item

`***`

***

* Las sintaxis presentadas son algunas que se pueden utilizar en Rmarkdown, pero hay otras que funcionan en [GitHub](https://help.github.com/en/articles/basic-writing-and-formatting-syntax):

- [x] Finish my changes
- [ ] Push my commits to GitHub
- [ ] Open a pull request


### Comandos b?sicos de git en consola


* `git init` creates a new Git repository.
* `git status` inspects the contents of the working directory and staging area.
* `git add` adds files from the working directory to the staging area.
* `git diff` shows the difference between the working directory and the staging area.
* `git commit` permanently stores file changes from the staging area in the repository.
* `git log` shows a list of all previous commits.

https://github.com/DGIIMUnderground/DGIIM1/blob/master/guias/github.md
https://github.com/JJ/aprende-git/blob/master/texto/uso_basico.md


###git reset review

To better understand git reset commit_SHA, notice the diagram on the right. Each circle represents a commit.

**Before reset:**

* `HEAD` is at the most recent commit

**After resetting:**

* `HEAD` goes to a previously made commit of your choice
* The gray commits are no longer part of your project
* You have in essence rewound the project's history

* `git checkout HEAD filname`: Discards changes in the working directory.
* `git reset HEAD filname`: Unstages file changes in the staging area.
* `git reset commit_SHA`: Resets to a previous commit in your commit history.


**git branch:**

Git branching allows users to experiment with different versions of a project by checking out separate branches to work on.
The following commands are useful in the Git branch workflow.

* `git branch`: Lists all a Git project's branches.
* `git branch branch_name`: Creates a new branch.
* `git checkout branch_name`: Used to switch from one branch to another.
* `git merge branch_name`: Used to join file changes from one branch to another.
* `git branch -d branch_name`: Deletes the branch specified.


## Iniciando con Git y GitHub


#### BitHub

Para usar **GitHub** se debe crear una cuenta en <https://github.com/>.

#### Git

Para instalar **Git** visitar [git-scm.com/downloads](https://git-scm.com/downloads).

Luego de instalar Git se debe configurar el nombre de usuario y email.

**Configurar Git**

1. Abrir "Git Bash" 
2. Configurar nombre de usuario:

`git config --global user.name "Nombre que quieras mostrar"`

3. Configurar email del usuario:

`git config --global user.email "correo@email.com"`

Ver <https://help.github.com/en/articles/set-up-git> para mas informaci?n.

Para crear un repositorio en Git se suele usar las linas de comandos, algunas son:

**Lineas de comandos:**

* `ls` 
* `pwd`
* `cd`
* `cd ..`
* `mkdir`: crea un directorio
* `touch`: crea un archivo

**Ahora us?moslas para crear un repositorio:**

1. `mkdir git_practice` to make a new directory to practice.
2. `cd git_practice` to make the new directory your working directory.
3. `git init` to turn the current, empty directory into a fresh Git repository.
4. `echo "Hello Git and GitHub" >> README.txt` to create a new README file (more on this later) with some sample text.
5. `git add README.txt` to add the new file to the Git staging area.
6. `git commit -m "First commit"` to make your first commit with the new README file.



A remote is a Git repository that lives outside your Git project folder. Remotes can live on the web, on a shared network or even in a separate folder on your local computer.
The Git Collaborative Workflow are steps that enable smooth project development when multiple collaborators are working on the same Git project.
We also learned the following commands

* `git clone`: Creates a local copy of a remote.
* `git remote -v`: Lists a Git project's remotes.
* `git fetch`: Fetches work from the remote into the local copy.
* `git merge origin/master`: Merges origin/master into your local branch.
* `git push origin <branch_name>`: Pushes a local branch to the origin remote.

Git projects are usually managed on Github, a website that hosts Git projects for millions of users. With Github you can access your projects from anywhere in the world by using the basic workflow you learned here.


> Para subir este documento a github: en yalm puse `output: github_document` para que cree un archivo (.md) aparte del (.Rmd). 
en la consola de GIT BACH me dirig? a la carpeta local que contiene este archivo, luego revis? `git status` , a?ad? los archivos con `git add .` (el punto es para subir todos los documentos q cambiaron, el .Rmd y .md, y los sub? para comparar las salidas), luego un commit `git commit -m "formato github(por ejemplo)"` y finalmente un push, `git push`. Ahora se puede ver el documento en la pagina de GitHub con los render correspondientes de las sintaxis Markdown (el .md). 


**Ahora, c?mo publicar un documento tipo blog hosteando la p?gina con GitHub Pages**

**Fuente:** (https://resources.github.com/whitepapers/github-and-rstudio/)

(En RStudio ir a Tools> Global options> Git y en el PATH debe estar git.exe C:/Program Files/Git/bin/git.exe )

1. Crear nuevo proyecto: File > New project > Version control > Git
2. Pegar la URL del repositorio creado en GitHub , en mi caso: https://github.com/patosaid/apuntes_git_rmarkdown.git
3.  Clic en crear. (esto hace que se clone el repo en la carpeta q elegí... quedó la cagá, tengo un repo clonado dentro de un repo...)
4. Crear un documento (este mismo)

**Commit and push the changes to GitHub**

After you have created the R Markdown document and finished making your changes, it is time to commit them.

1. In RStudio click the Git tab in the upper right pane.( bien ahora me aparece )
2. Click Commit.
3. In the Review changes view, check the staged box for all files.
4. Add a commit message, for example Add initial speed and distance report.
5. Click Commit.
6. Click the Pull button to fetch any remote changes.
7. Click the Push button to push your changes to the remote repository.
8. On GitHub, navigate to the Code tab of the repository to see the changes.














